#!/bin/bash

echo "Building admin.goodcity.hk [production]" && \
EMBER_CLI_CORDOVA=0 ember build --environment=production && \
echo "Removing existing files on admin.goodcity.hk" && \
ssh deployer@admin.goodcity.hk 'rm -rf /var/www/html/admin.goodcity.hk/*' && \
echo "Uploading new files to admin.goodcity.hk" && \
scp -r dist/* deployer@admin.goodcity.hk:/var/www/html/admin.goodcity.hk/
